# Generated by Django 5.2.6 on 2025-09-20 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255, null=True)),
                ('tipoevento', models.TextField(max_length=255)),
                ('dataI', models.IntegerField()),
                ('dataF', models.IntegerField()),
                ('horarioI', models.IntegerField()),
                ('horarioF', models.IntegerField()),
                ('local', models.TextField(max_length=255)),
                ('quantPart', models.IntegerField()),
                ('organResp', models.TextField(max_length=255)),
                ('vagas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=255)),
                ('senha', models.TextField(max_length=255)),
                ('telefone', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id_inscricao', models.AutoField(primary_key=True, serialize=False)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_cert', models.AutoField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
