# Generated by Django 5.2.6 on 2025-09-21 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='evento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.evento'),
        ),
    ]
