# Generated by Django 5.2.6 on 2025-09-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idade',
            new_name='senha',
        ),
    ]
