# Generated by Django 5.2.6 on 2025-09-21 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_certificado_evento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='evento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento'),
        ),
    ]
