# Generated by Django 5.2.6 on 2025-09-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_certificado_evento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='data_evento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='nome_evento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
