# Generated by Django 5.2.6 on 2025-09-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_idade_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('tipoevento', models.TextField(max_length=255)),
                ('dataI', models.IntegerField()),
                ('dataF', models.IntegerField()),
                ('horarioI', models.IntegerField()),
                ('horarioF', models.IntegerField()),
                ('local', models.TextField(max_length=255)),
                ('quantPart', models.IntegerField()),
                ('organResp', models.TextField(max_length=255)),
                ('vagas', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(max_length=255),
        ),
    ]
