# Generated by Django 5.2.6 on 2025-09-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_evento_alter_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id_inscricao', models.AutoField(primary_key=True, serialize=False)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
