# Generated by Django 5.2.6 on 2025-09-21 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_certificado_data_evento_certificado_nome_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='evento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.evento'),
        ),
    ]
