# Generated by Django 5.2.6 on 2025-09-19 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_evento_nome_alter_usuario_id_usuario_inscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default=0, max_length=13, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser inserido no formato: '+9999999999999'.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
