# Generated by Django 5.2.6 on 2025-09-21 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_certificado_evento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='data_evento',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='nome_evento',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='evento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento'),
        ),
    ]
