# Generated by Django 5.2.6 on 2025-09-20 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser inserido no formato: '+9999999999999'.", regex='^\\+?1?\\d{13}$')]),
        ),
    ]
