# Generated by Django 5.2.6 on 2025-09-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_certificado_data_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='emitido',
            field=models.BooleanField(default=False),
        ),
    ]
