# Generated by Django 5.2.6 on 2025-09-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_evento_emitido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='instituicao',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
