# Generated by Django 5.2.6 on 2025-09-20 15:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser inserido no formato: '+9999999999999'.", regex='^\\+?1?\\d{13}$')]),
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id_cert', models.AutoField(primary_key=True, serialize=False)),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
