# Generated by Django 5.2.6 on 2025-09-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_usuario_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('estudante', 'Estudante'), ('professor', 'Professor')], default='estudante', max_length=50),
        ),
    ]
