# Generated by Django 5.2.6 on 2025-09-20 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados',
            name='data_emissao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
