# Generated by Django 5.2.6 on 2025-09-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_certificados_data_emissao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificados',
            new_name='Certificado',
        ),
    ]
