# Generated by Django 5.2.6 on 2025-10-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='assinatura',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
