# Generated by Django 5.2.6 on 2025-09-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_rename_certificados_certificado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='evento_id',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
