# Generated by Django 5.2.6 on 2025-10-03 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_evento_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='evento_assinatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificado_assinados', to='login.evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificado',
            name='evento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificado_evento', to='login.evento'),
        ),
    ]
