# Generated by Django 5.2.6 on 2025-10-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_certificado_evento_assinatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='evento_assinatura',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='evento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento'),
        ),
    ]
