# Generated by Django 5.2.6 on 2025-09-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_rename_evento_id_certificado_evento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='evento',
            new_name='evento_id',
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
