# Generated by Django 5.2.6 on 2025-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_certificado_evento_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='evento_assinatura',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
