# Generated by Django 5.2.6 on 2025-10-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_certificado_evento_assinatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='evento_assinatura',
            new_name='assinatura',
        ),
    ]
