# Generated by Django 5.2.6 on 2025-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_rename_evento_assinatura_certificado_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='horas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
