# Generated by Django 5.2.6 on 2025-10-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_evento_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='horas',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
