# Generated by Django 5.2.6 on 2025-10-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_certificado_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('estudante', 'Estudante'), ('professor', 'Professor'), ('organizador', 'Organizador')], default='estudante', max_length=50),
        ),
    ]
