# Generated by Django 5.2.6 on 2025-10-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.TextField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
