# Generated by Django 5.2.6 on 2025-10-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_usuario_sobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.TextField(max_length=50)),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.evento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
        ),
    ]
