# Generated by Django 5.2.6 on 2025-10-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='evento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.evento'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.usuario'),
        ),
    ]
