# Generated by Django 5.2.6 on 2025-10-27 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_registro_evento_id_alter_registro_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registro',
            name='evento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.evento'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='usuario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.usuario'),
        ),
    ]
