# Generated by Django 5.2.6 on 2025-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_registro_hora_alter_registro_evento_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='id_registro',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
