# Generated by Django 5.2.6 on 2025-10-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_alter_registro_evento_id_alter_registro_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='evento_id',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='usuario_id',
        ),
    ]
