# Generated by Django 5.2.6 on 2025-10-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_remove_registro_evento_id_remove_registro_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='evento_id',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='usuario_id',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
