# Generated by Django 5.2.6 on 2025-10-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_registro_evento_id_registro_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='dataF',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dataI',
            field=models.DateField(),
        ),
    ]
